#!/usr/bin/env bash
# This script displays 1 - 20, BL from China after 4, BL from Japan after 9, and BL from Italy after 17
i=1
while [ "$i" -le 20 ]
do
case "$i" in
4)
echo "$i"
echo "bad luck from China"
;;
9)
echo "$i"
echo "bad luck from Japan"
;;
17)
echo "$i"
echo "bad luck from Italy"
;;
*)
echo "$i"
;;
esac
i=$(( i + 1 ))
done