#!/usr/bin/env bash
# This script displays time for 12 hours and 59 minutes
i=0
echo "Hour: $i"
while [ "$i" -le 11 ]
do
j=1
while [ "$j" -le 59 ]
do
if [ "$j" -eq 59 ]
then
echo "$j"
i=$(( i + 1 ))
echo "Hour: $i"
else
echo "$j"
fi
j=$(( j + 1 ))
done
done
