#!/bin/bash
# This script changes IP adress of localhost and facebook.com
if [ "$EUID" -ne 0 ];
then
    exit 1
fi

localhost_ip = "127.0.0.2"
facebook_ip = "8.8.8.8"

localhost_val="${localhost_ip} localhost"
facebook_val="${facebook_ip} facebook.com"

echo "$localhost_val" >> /etc/hosts
echo "$facebook_val" >> /etc/hosts
