#!/usr/bin/env bash
# This script changes IP adress of localhost and facebook.com
# localhost resolves to 127.0.0.2
# facebook.com resollves to 8.8.8.8

cp /etc/hosts ~hosts.new
echo "127.0.0.2     localhost" > ~/hosts.new
echo "8.8.8.8     facebook.com" >> ~/hosts.new
cp -f ~hosts.new /etc/hosts
