#!/bin/bash
# This script changes IP adress of localhost and facebook.com
if [ "$EUID" -ne 0 ]
then
    exit 1
fi

echo "127.0.0.2	      http://localhost" >> /etc/hosts
echo "8.8.8.8	      facebook.com" >> /etc/hosts
